# Site settings
title: My Website
email: mail.shulhan@gmail.com
description: Gini aja cukup
url: https://bukanmedium.github.io/Tes_gpt/

# Build settings
paginate: 10
paginate_path: /page/:num
markdown: kramdown
highlighter: rouge
permalink: pretty
exclude:
  - .DS_Store

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-lazy-load-images


# Navigation
navigation:
  - title: Home
    url: https://bukanmedium.github.io/Tes_gpt/
  - title: Blog
    url: https://bukanmedium.github.io/Tes_gpt/blog/
  - title: About
    url: https://bukanmedium.github.io/Tes_gpt/about/
