# Site settings
title: My Website
email: myemail@example.com
description: A description of my website
url: https://mywebsite.com

# Build settings
paginate: 10
paginate_path: /page/:num
markdown: kramdown
highlighter: rouge
permalink: pretty
exclude:
  - .DS_Store

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-lazy-load-images


# Navigation
navigation:
  - title: Home
    url: /
  - title: Blog
    url: /blog/
  - title: About
    url: /about/
